export const CATEGORY_OPTIONS = [
  { label: "Class 1", value: "class-1" },
  { label: "Class 2", value: "class-2" },
  { label: "Class 3", value: "class-3" },
  { label: "Class 4", value: "class-4" },
  { label: "Class 5", value: "class-5" },
  { label: "Class 6", value: "class-6" },
  { label: "Class 7", value: "class-7" },
  { label: "Class 8", value: "class-8" },
  { label: "Class 9", value: "class-9" },
  { label: "Class 10", value: "class-10" },
  { label: "Class 10", value: "class-11" },
  { label: "Class 12", value: "class-12" },
  { label: "State Entrance", value: "state-entrance" },
  { label: "NEET", value: "neet" },
  { label: "Banking", value: "banking" },
  { label: "Railway", value: "railway" },
  { label: "Music", value: "music" },
  { label: "Dance", value: "dance" },
  { label: "Competitive Programming", value: "competitive-programming" },
  { label: "Web Development", value: "web-development" },
  { label: "Mobile Development", value: "mobile-development" },
  {label: "Software Development", value: "software-development" },
  { label: "AI/ML", value: "ai-ml" },
  { label: "Other", value: "other" },
];


